name: pipeline

on: [push, pull_request]

jobs:
  pipeline:
    name: pipeline
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Setup PureScript
        uses: purescript-contrib/setup-purescript@main
        with:
          purescript: latest
          psa: latest
          purs-tidy: latest

      - name: Cache PureScript dependencies
        uses: actions/cache@v4
        with:
          key: ${{ runner.os }}-spago-${{ hashFiles('**/spago.lock') }}
          path: |
            .spago
            output

      - uses: actions/setup-node@v6
        with:
          node-version: latest

      - name: Install npm packages
        run: npm install -g spago@next

      - name: Check formatting
        run: npx purs-tidy check src test

      - name: Install dependencies
        run: npx spago install

      - name: Build
        run: npx spago build --strict

      - name: Test
        run: npx spago test --strict
